-- Generated by Oracle SQL Developer Data Modeler 18.2.0.179.0806
--   at:        2018-09-12 12:05:17 AEST
--   site:      Oracle Database 11g
--   type:      Oracle Database 11g
SET ECHO ON;

SPOOL mc_sch.txt;


DROP SEQUENCE cotractor_detail_cont_no_seq;

DROP SEQUENCE guest_guest_no_seq;

DROP SEQUENCE manager_mang_id_seq;

DROP SEQUENCE resort_res_id_seq;

DROP TABLE booking CASCADE CONSTRAINTS;

DROP TABLE cabin CASCADE CONSTRAINTS;

DROP TABLE cabin_cleaning CASCADE CONSTRAINTS;

DROP TABLE cabin_rate CASCADE CONSTRAINTS;

DROP TABLE contractor_history CASCADE CONSTRAINTS;

DROP TABLE cotractor_detail CASCADE CONSTRAINTS;

DROP TABLE guest CASCADE CONSTRAINTS;

DROP TABLE manager CASCADE CONSTRAINTS;

DROP TABLE point_of_interest CASCADE CONSTRAINTS;

DROP TABLE resort CASCADE CONSTRAINTS;

DROP TABLE review CASCADE CONSTRAINTS;

DROP TABLE town CASCADE CONSTRAINTS;

CREATE TABLE booking (
    guest_no           NUMBER(7) NOT NULL,
    cab_number         NUMBER(7) NOT NULL,
    res_id             NUMBER(7) NOT NULL, 
--  end_date : end_date of booking
    end_date           DATE, 
--  number_of_adults 
    number_of_adults   NUMBER(2) NOT NULL,
    no_of_children     NUMBER(2) NOT NULL,
    no_of_pets         NUMBER(1) NOT NULL,
    total_charge       NUMBER(5,2) NOT NULL,
    start_date         DATE NOT NULL
);

ALTER TABLE booking ADD CONSTRAINT check_total_charge CHECK ( total_charge > 0 );

COMMENT ON COLUMN booking.guest_no IS
    'guest_no : Guest number given by monash cabin.';

COMMENT ON COLUMN booking.cab_number IS
    'cabin_number : cabin_number';

COMMENT ON COLUMN booking.res_id IS
    'resortid : Resort id';

COMMENT ON COLUMN booking.number_of_adults IS
    'number_of_adults : Total number of adults.';

COMMENT ON COLUMN booking.no_of_children IS
    'number_of_children : Total number of adress.';

COMMENT ON COLUMN booking.no_of_pets IS
    'no_of_pets : number of pets.';

COMMENT ON COLUMN booking.total_charge IS
    'total_charge : total charge of booking.';

COMMENT ON COLUMN booking.start_date IS
    'start_date = start date of booking';

ALTER TABLE booking
    ADD CONSTRAINT booking_pk PRIMARY KEY ( cab_number,
                                            res_id,
                                            start_date );

CREATE TABLE cabin (
    cab_number               NUMBER(7) NOT NULL,
    res_id                   NUMBER(7) NOT NULL,
    number_of_bedrooms       NUMBER(5) NOT NULL,
    sleeping_capacity        NUMBER(4) NOT NULL,
    standard_cleaning_time   NUMBER(4,2) NOT NULL,
    description              VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN cabin.cab_number IS
    'cabin_number : cabin_number';

COMMENT ON COLUMN cabin.res_id IS
    'resortid : Resort id';

COMMENT ON COLUMN cabin.number_of_bedrooms IS
    'number_of_bedrooms : total number of bedrooms';

COMMENT ON COLUMN cabin.sleeping_capacity IS
    'sleeping_capacity : sleeping capacity of cabin';

COMMENT ON COLUMN cabin.standard_cleaning_time IS
    'standard_cleaning_time : standard cleaning time of cabin';

COMMENT ON COLUMN cabin.description IS
    'description';

ALTER TABLE cabin ADD CONSTRAINT cabin_pk PRIMARY KEY ( cab_number,
                                                        res_id );

CREATE TABLE cabin_cleaning (
    date_cleaned           DATE NOT NULL,
    cont_no                NUMBER(7) NOT NULL,
    cab_number             NUMBER(7) NOT NULL,
    res_id                 NUMBER(7) NOT NULL,
    actual_cleaning_time   NUMBER(4,2) NOT NULL,
    cleaning_charge        NUMBER(7,2) NOT NULL
);

COMMENT ON COLUMN cabin_cleaning.date_cleaned IS
    'date_cleaned : Date when cabin was cleaned';

COMMENT ON COLUMN cabin_cleaning.cont_no IS
    'c_no : Assigned contractor number';

COMMENT ON COLUMN cabin_cleaning.cab_number IS
    'cabin_number : cabin_number';

COMMENT ON COLUMN cabin_cleaning.res_id IS
    'resortid : Resort id';

COMMENT ON COLUMN cabin_cleaning.actual_cleaning_time IS
    'actual_cleaning_time : actual cleaning time of the cabin';

COMMENT ON COLUMN cabin_cleaning.cleaning_charge IS
    'cleaning_charge : Cleaning charge of cabin';

ALTER TABLE cabin_cleaning
    ADD CONSTRAINT cabin_cleaning_pk PRIMARY KEY ( date_cleaned,
                                                   cab_number,
                                                   res_id );

CREATE TABLE cabin_rate (
    time_of_the_year   DATE NOT NULL,
    cab_number         NUMBER(7) NOT NULL,
    res_id             NUMBER(7) NOT NULL,
    cabin_rate         NUMBER(7,2) NOT NULL
);

ALTER TABLE cabin_rate ADD CONSTRAINT check_cabin_rate CHECK ( cabin_rate > 0 );

COMMENT ON COLUMN cabin_rate.time_of_the_year IS
    'time_of_the_year : Month of the year';

COMMENT ON COLUMN cabin_rate.cab_number IS
    'cabin_number : cabin_number';

COMMENT ON COLUMN cabin_rate.res_id IS
    'resortid : Resort id';

ALTER TABLE cabin_rate
    ADD CONSTRAINT cabin_rate_pk PRIMARY KEY ( time_of_the_year,
                                               cab_number,
                                               res_id );

CREATE TABLE contractor_history (
    start_date             DATE NOT NULL,
    cont_no                NUMBER(7) NOT NULL,
    end_date               DATE,
    contract_hourly_rate   NUMBER(7,2) NOT NULL,
    contract_type          VARCHAR2(10) NOT NULL
);

ALTER TABLE contractor_history ADD CONSTRAINT check_contract_hourly_rate CHECK ( contract_hourly_rate > 0 );

ALTER TABLE contractor_history
    ADD CONSTRAINT check_contract_type CHECK ( contract_type IN (
        'casual',
        'fixed'
    ) );

COMMENT ON COLUMN contractor_history.start_date IS
    'start_date : Contract start_date';

COMMENT ON COLUMN contractor_history.cont_no IS
    'c_no : Assigned contractor number';

COMMENT ON COLUMN contractor_history.end_date IS
    'end_date : End date';

COMMENT ON COLUMN contractor_history.contract_hourly_rate IS
    'contract_hourly_rate : contract hourly rate';

COMMENT ON COLUMN contractor_history.contract_type IS
    'contract_type : type of the contract';

ALTER TABLE contractor_history ADD CONSTRAINT contractor_history_pk PRIMARY KEY ( start_date,
                                                                                  cont_no );

CREATE TABLE cotractor_detail (
    cont_no          NUMBER(7) NOT NULL, 
--  first_name : first name of contractor
    first_name       VARCHAR2(50) NOT NULL,
    postal_address   VARCHAR2(50) NOT NULL, 
--  phone_number : phone number of contractor
    phone_number     CHAR(10) NOT NULL, 
--  last_name : last name of contractor.
    last_name        VARCHAR2(50) NOT NULL
);

COMMENT ON COLUMN cotractor_detail.cont_no IS
    'c_no : Assigned contractor number';

COMMENT ON COLUMN cotractor_detail.first_name IS
    'contractor_name : name of the contractor';

COMMENT ON COLUMN cotractor_detail.postal_address IS
    'postal_address : postal address of contractor';

ALTER TABLE cotractor_detail ADD CONSTRAINT contractor_detail_pk PRIMARY KEY ( cont_no );

CREATE TABLE guest (
    guest_no       NUMBER(7) NOT NULL,
    guest_name     VARCHAR2(50) NOT NULL,
    address        VARCHAR2(50) NOT NULL,
    postal_code    NUMBER(5) NOT NULL,
    country        VARCHAR2(50) NOT NULL,
    email          VARCHAR2(50),
    phone_number   NUMBER(10) NOT NULL
);

COMMENT ON COLUMN guest.guest_no IS
    'guest_no : Guest number given by monash cabin.';

COMMENT ON COLUMN guest.guest_name IS
    'guest_name : guest name';

COMMENT ON COLUMN guest.address IS
    'address : guest street adress';

COMMENT ON COLUMN guest.postal_code IS
    'postal_code : guest postal code';

COMMENT ON COLUMN guest.country IS
    'country : country name of guest';

COMMENT ON COLUMN guest.email IS
    'email : email address of guest';

COMMENT ON COLUMN guest.phone_number IS
    'phone_number : phone number of guest';

ALTER TABLE guest ADD CONSTRAINT guest_pk PRIMARY KEY ( guest_no );

CREATE TABLE manager ( 
--  m_id : ID of manager.
    mang_id          NUMBER(7) NOT NULL, 
--  manager_name
    manager_name     VARCHAR2(50) NOT NULL,
    street_address   VARCHAR2(50) NOT NULL,
    town             VARCHAR2(50) NOT NULL,
    post_code        NUMBER(5) NOT NULL,
    phone_no         NUMBER(10) NOT NULL
);

COMMENT ON COLUMN manager.manager_name IS
    'manager_name : manager name';

COMMENT ON COLUMN manager.street_address IS
    'street_address : address of manager';

COMMENT ON COLUMN manager.town IS
    'town : manager''s town name';

COMMENT ON COLUMN manager.post_code IS
    'post_code : manager''s post code';

COMMENT ON COLUMN manager.phone_no IS
    'phone_no : manager''s phone number.';

ALTER TABLE manager ADD CONSTRAINT manager_pk PRIMARY KEY ( mang_id );

CREATE TABLE point_of_interest (
    "long"              NUMBER(7) NOT NULL,
    lat                 NUMBER(7) NOT NULL, 
--  street_address
    street_address      VARCHAR2(50) NOT NULL,
    poi_name            VARCHAR2(50) NOT NULL,
    opening_hour        VARCHAR2(10) NOT NULL,
    poi_type            VARCHAR2(50) NOT NULL,
    brief_description   VARCHAR2(50)
);

COMMENT ON COLUMN point_of_interest."long" IS
    'long : longitude of the town';

COMMENT ON COLUMN point_of_interest.lat IS
    'lati : Latitude of town';

COMMENT ON COLUMN point_of_interest.street_address IS
    'street_address : address of street';

COMMENT ON COLUMN point_of_interest.poi_name IS
    'poi_name : point of interest name';

COMMENT ON COLUMN point_of_interest.poi_type IS
    'poi_type : Point of interest type';

COMMENT ON COLUMN point_of_interest.brief_description IS
    'brief_description : Brief description of pont of interest';

ALTER TABLE point_of_interest
    ADD CONSTRAINT point_of_interest_pk PRIMARY KEY ( "long",
                                                      lat,
                                                      street_address,
                                                      poi_name );

CREATE TABLE resort (
    res_id            NUMBER(7) NOT NULL,
    "long"            NUMBER(7) NOT NULL,
    lat               NUMBER(7) NOT NULL, 
--  m_id : ID of manager.
    mang_id           NUMBER(7) NOT NULL,
    resort_name       VARCHAR2(50) NOT NULL,
    pet_permission    VARCHAR2(10) NOT NULL,
    manager_present   VARCHAR2(50) NOT NULL,
    resort_adress     VARCHAR2(60) NOT NULL,
    resort_rating     NUMBER(5) NOT NULL
);

ALTER TABLE resort
    ADD CONSTRAINT check_pet_permission CHECK ( pet_permission IN (
        'no',
        'yes'
    ) );

ALTER TABLE resort
    ADD CONSTRAINT check_manager_present CHECK ( manager_present IN (
        'no',
        'yes'
    ) );

COMMENT ON COLUMN resort.res_id IS
    'resortid : Resort id';

COMMENT ON COLUMN resort."long" IS
    'long : longitude of the town';

COMMENT ON COLUMN resort.lat IS
    'lati : Latitude of town';

COMMENT ON COLUMN resort.resort_name IS
    'resort_name : name of the resort';

COMMENT ON COLUMN resort.pet_permission IS
    'pet_permission : permission of pet in the resort';

COMMENT ON COLUMN resort.manager_present IS
    'manager_present : permission of pet in the resort';

COMMENT ON COLUMN resort.resort_adress IS
    'street_address : street address of the resort';

COMMENT ON COLUMN resort.resort_rating IS
    'resort_rating : Average of pet , manager present and rating from review.';

ALTER TABLE resort ADD CONSTRAINT resort_pk PRIMARY KEY ( res_id );

CREATE TABLE review (
    review_date   DATE NOT NULL,
    guest_no      NUMBER(7) NOT NULL,
    res_id        NUMBER(7) NOT NULL, 
--  rating : review rating
    rating        NUMBER(5) NOT NULL, 
--  comment : comment by guest 
    "comment"     VARCHAR2(50)
);

ALTER TABLE review
    ADD CONSTRAINT check_rating CHECK ( rating BETWEEN 1 AND 5 );

COMMENT ON COLUMN review.review_date IS
    'review_date : Date of review';

COMMENT ON COLUMN review.guest_no IS
    'guest_no : Guest number given by monash cabin.';

COMMENT ON COLUMN review.res_id IS
    'resortid : Resort id';

ALTER TABLE review
    ADD CONSTRAINT review_pk PRIMARY KEY ( review_date,
                                           guest_no,
                                           res_id );

CREATE TABLE town (
    "long"                      NUMBER(7) NOT NULL,
    lat                         NUMBER(7) NOT NULL,
    town_name                   VARCHAR2(50) NOT NULL,
    state                       VARCHAR2(10) NOT NULL,
    summer_avg_temp             NUMBER(4,2) NOT NULL,
    winter_avg_temp             NUMBER(4,2) NOT NULL,
    elevation_above_sea_level   NUMBER(7,2),
    population                  NUMBER(15)
);

COMMENT ON COLUMN town."long" IS
    'long : longitude of the town';

COMMENT ON COLUMN town.lat IS
    'lati : Latitude of town';

COMMENT ON COLUMN town.town_name IS
    'town_name : Name of the town';

COMMENT ON COLUMN town.state IS
    'state : town''s state name';

COMMENT ON COLUMN town.summer_avg_temp IS
    'summer_avg_temp : Town''s elevation above sea level';

COMMENT ON COLUMN town.winter_avg_temp IS
    ' winter_avg_temp : Town''s elevation above sea level';

COMMENT ON COLUMN town.elevation_above_sea_level IS
    'elevation_above_sea_level : Town''s elevation above sea level';

COMMENT ON COLUMN town.population IS
    'population : population of town.';

ALTER TABLE town ADD CONSTRAINT town_pk PRIMARY KEY ( "long",
                                                      lat );

ALTER TABLE booking
    ADD CONSTRAINT cabin_booking FOREIGN KEY ( cab_number,
                                               res_id )
        REFERENCES cabin ( cab_number,
                           res_id );

ALTER TABLE cabin_cleaning
    ADD CONSTRAINT cabin_cabin_cleaning FOREIGN KEY ( cab_number,
                                                      res_id )
        REFERENCES cabin ( cab_number,
                           res_id );

ALTER TABLE cabin_rate
    ADD CONSTRAINT cabin_cabin_rate FOREIGN KEY ( cab_number,
                                                  res_id )
        REFERENCES cabin ( cab_number,
                           res_id );

ALTER TABLE cabin_cleaning
    ADD CONSTRAINT conr_detail_cab_cleaning FOREIGN KEY ( cont_no )
        REFERENCES cotractor_detail ( cont_no );

ALTER TABLE contractor_history
    ADD CONSTRAINT conr_detail_conr_history FOREIGN KEY ( cont_no )
        REFERENCES cotractor_detail ( cont_no );

ALTER TABLE booking
    ADD CONSTRAINT guest_booking FOREIGN KEY ( guest_no )
        REFERENCES guest ( guest_no );

ALTER TABLE review
    ADD CONSTRAINT guest_review FOREIGN KEY ( guest_no )
        REFERENCES guest ( guest_no );

ALTER TABLE resort
    ADD CONSTRAINT manager_resort FOREIGN KEY ( mang_id )
        REFERENCES manager ( mang_id );

ALTER TABLE cabin
    ADD CONSTRAINT resort_cabin FOREIGN KEY ( res_id )
        REFERENCES resort ( res_id );

ALTER TABLE review
    ADD CONSTRAINT resort_review FOREIGN KEY ( res_id )
        REFERENCES resort ( res_id );

ALTER TABLE point_of_interest
    ADD CONSTRAINT town_point_of_interest FOREIGN KEY ( "long",
                                                        lat )
        REFERENCES town ( "long",
                          lat );

ALTER TABLE resort
    ADD CONSTRAINT town_resort FOREIGN KEY ( "long",
                                             lat )
        REFERENCES town ( "long",
                          lat );

CREATE SEQUENCE cotractor_detail_cont_no_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE guest_guest_no_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE manager_mang_id_seq START WITH 1 NOCACHE ORDER;

CREATE SEQUENCE resort_res_id_seq START WITH 1 NOCACHE ORDER;



-- Oracle SQL Developer Data Modeler Summary Report: 
-- 
-- CREATE TABLE                            12
-- CREATE INDEX                             0
-- ALTER TABLE                             31
-- CREATE VIEW                              0
-- ALTER VIEW                               0
-- CREATE PACKAGE                           0
-- CREATE PACKAGE BODY                      0
-- CREATE PROCEDURE                         0
-- CREATE FUNCTION                          0
-- CREATE TRIGGER                           0
-- ALTER TRIGGER                            0
-- CREATE COLLECTION TYPE                   0
-- CREATE STRUCTURED TYPE                   0
-- CREATE STRUCTURED TYPE BODY              0
-- CREATE CLUSTER                           0
-- CREATE CONTEXT                           0
-- CREATE DATABASE                          0
-- CREATE DIMENSION                         0
-- CREATE DIRECTORY                         0
-- CREATE DISK GROUP                        0
-- CREATE ROLE                              0
-- CREATE ROLLBACK SEGMENT                  0
-- CREATE SEQUENCE                          4
-- CREATE MATERIALIZED VIEW                 0
-- CREATE MATERIALIZED VIEW LOG             0
-- CREATE SYNONYM                           0
-- CREATE TABLESPACE                        0
-- CREATE USER                              0
-- 
-- DROP TABLESPACE                          0
-- DROP DATABASE                            0
-- 
-- REDACTION POLICY                         0
-- 
-- ORDS DROP SCHEMA                         0
-- ORDS ENABLE SCHEMA                       0
-- ORDS ENABLE OBJECT                       0
-- 
-- ERRORS                                   0
-- WARNINGS                                 0


SET ECHO OFF;
